yanagishima = {
	version: '5.0',
	sitename: 'yanagishima',
	domain: '',
	apis: {
		datasource: '/datasource',
		tableList: '/tableList?datasource={datasource}&catalog={catalog}',
		presto: '/presto?datasource={datasource}',
		prestoAsync: '/prestoAsync?datasource={datasource}',
		queryStatus: '/queryStatus?datasource={datasource}&queryid={queryid}',
		query: '/query?datasource={datasource}',
		history: '/history?datasource={datasource}&queryid={queryid}',
		historyStatus: '/historyStatus?datasource={datasource}&queryid={queryid}',
		queryHistory: '/queryHistory?datasource={datasource}',
		download: '/download?datasource={datasource}&queryid={queryid}',
		csvdownload: '/csvdownload?datasource={datasource}&queryid={queryid}',
		publish: '/publish?datasource={datasource}&queryid={queryid}',
		bookmark: '/bookmark?datasource={datasource}',
		format: '/format',
		kill: '/kill?datasource={datasource}&queryid={queryid}',
		detail: '/queryDetail?datasource={datasource}&queryid={queryid}',
		shareHistory: '/share/shareHistory?publish_id={publish_id}',
		shareDownload: '/share/download?publish_id={publish_id}',
		shareCsvDownload: '/share/csvdownload?publish_id={publish_id}',
		toValuesQuery: '/toValuesQuery'
	},
	links: {
		about_this: 'https://github.com/wyukawa/yanagishima/blob/master/README.md',
		bugs_feedback: 'https://github.com/wyukawa/yanagishima/issues',
		mail_admin: '',
	},
	hiddenQuery_prefix: '/* yanagishima */',
	columnDate_names: [
		'dt',
		'yyyymmdd',
		'log_date'
	],
	default_catalog: '',
	snippets: [{
			label: "SELECT * FROM ... LIMIT 100",
			sql: "SELECT {columns} FROM {catalog}.{schema}.{table} LIMIT 100",
			enable: ['BASE TABLE', 'VIEW']
		},
		{
			label: "SELECT * FROM ... WHERE ${column_date}=${yesterday} LIMIT 100",
			sql: "SELECT {columns} FROM {catalog}.{schema}.{table} WHERE {column_date}='{yesterday}' LIMIT 100",
			enable: ['BASE TABLE', 'VIEW']
		},
		{
			label: "SHOW PRESTO VIEW DDL",
			sql: "SELECT VIEW_DEFINITION FROM {catalog}.INFORMATION_SCHEMA.VIEWS WHERE table_catalog='{catalog}' AND table_schema='{schema}' AND table_name='{table}'",
			enable: ['VIEW']
		},
		{
			label: "SHOW CREATE TABLE ...",
			sql: "SHOW CREATE TABLE {catalog}.{schema}.{table}",
			enable: ['BASE TABLE']
		},
		{
			label: "SHOW PARTITIONS FROM ...",
			sql: "SHOW PARTITIONS FROM {catalog}.{schema}.{table}",
			enable: ['BASE TABLE']
		},
		{
			label: "DESCRIBE ...",
			sql: "DESCRIBE {catalog}.{schema}.{table}",
			enable: ['BASE TABLE', 'VIEW']
		}
	],
	themes: [
		'ambiance',
		'chaos',
		'chrome',
		'clouds',
		'clouds_midnight',
		'cobalt',
		'crimson_editor',
		'dawn',
		'eclipse',
		'github',
		'idle_fingers',
		'iplastic',
		'katzenmilch',
		'kuroir',
		'kr_theme',
		'merbivore',
		'merbivore_soft',
		'mono_industrial',
		'monokai',
		'pastel_on_dark',
		'solarized_dark',
		'solarized_light',
		'sqlserver',
		'terminal',
		'textmate',
		'tomorrow',
		'tomorrow_night',
		'tomorrow_night_blue',
		'tomorrow_night_bright',
		'tomorrow_night_eighties',
		'twilight',
		'vibrant_ink',
		'xcode'
	],
	complate_list: {
		snippet: [
			"WHERE dt='{yesterday}' LIMIT 100",
			"WHERE yyyymmdd='{yesterday}' LIMIT 100",
			"WHERE log_date='{yesterday}' LIMIT 100",
		],
		function: [
			"abs",
			"acos",
			"approx_distinct",
			"approx_percentile",
			"approx_set",
			"arbitrary",
			"array_agg",
			"array_distinct",
			"array_intersect",
			"array_join",
			"array_max",
			"array_min",
			"array_position",
			"array_remove",
			"array_sort",
			"array_union",
			"asin",
			"atan",
			"atan2",
			"avg",
			"bar",
			"bit_count",
			"bitwise_and",
			"bitwise_and_agg",
			"bitwise_not",
			"bitwise_or",
			"bitwise_or_agg",
			"bitwise_xor",
			"bool_and",
			"bool_or",
			"cardinality",
			"cbrt",
			"ceil",
			"ceiling",
			"char2hexint",
			"checksum",
			"chr",
			"classify",
			"coalesce",
			"color",
			"concat",
			"contains",
			"corr",
			"cos",
			"cosh",
			"cosine_similarity",
			"count",
			"count_if",
			"covar_pop",
			"covar_samp",
			"cume_dist",
			"current_date",
			"current_time",
			"current_timestamp",
			"current_timezone",
			"date",
			"date_add",
			"date_diff",
			"date_format",
			"date_parse",
			"date_trunc",
			"day",
			"day_of_month",
			"day_of_week",
			"day_of_year",
			"degrees",
			"dense_rank",
			"dow",
			"doy",
			"e",
			"element_at",
			"empty_approx_set",
			"evaluate_classifier_predictions",
			"every",
			"exp",
			"features",
			"filter",
			"first_value",
			"flatten",
			"floor",
			"format_datetime",
			"from_base",
			"from_base64",
			"from_base64url",
			"from_big_endian_64",
			"from_hex",
			"from_iso8601_date",
			"from_iso8601_timestamp",
			"from_unixtime",
			"from_utf8",
			"geometric_mean",
			"greatest",
			"histogram",
			"hour",
			"index",
			"infinity",
			"is_finite",
			"is_infinite",
			"is_nan",
			"json_array_contains",
			"json_array_get",
			"json_array_length",
			"json_extract",
			"json_extract_scalar",
			"json_format",
			"json_parse",
			"json_size",
			"lag",
			"last_value",
			"lead",
			"learn_classifier",
			"learn_libsvm_classifier",
			"learn_libsvm_regressor",
			"learn_regressor",
			"least",
			"length",
			"like_pattern",
			"ln",
			"localtime",
			"localtimestamp",
			"log",
			"log10",
			"log2",
			"lower",
			"lpad",
			"ltrim",
			"map",
			"map_agg",
			"map_concat",
			"map_filter",
			"map_keys",
			"map_union",
			"map_values",
			"max",
			"max_by",
			"md5",
			"merge",
			"min",
			"min_by",
			"minute",
			"mod",
			"month",
			"multimap_agg",
			"nan",
			"normalize",
			"now",
			"nth_value",
			"ntile",
			"numeric_histogram",
			"objectid",
			"parse_datetime",
			"percent_rank",
			"pi",
			"pow",
			"power",
			"quarter",
			"radians",
			"rand",
			"random",
			"rank",
			"reduce",
			"regexp_extract",
			"regexp_extract_all",
			"regexp_like",
			"regexp_replace",
			"regexp_split",
			"regr_intercept",
			"regr_slope",
			"regress",
			"render",
			"replace",
			"reverse",
			"rgb",
			"round",
			"row_number",
			"rpad",
			"rtrim",
			"second",
			"sequence",
			"sha1",
			"sha256",
			"sha512",
			"shuffle",
			"sign",
			"sin",
			"slice",
			"split",
			"split_part",
			"split_to_map",
			"sqrt",
			"stddev",
			"stddev_pop",
			"stddev_samp",
			"strpos",
			"substr",
			"substring",
			"sum",
			"tan",
			"tanh",
			"timezone_hour",
			"timezone_minute",
			"to_base",
			"to_base64",
			"to_base64url",
			"to_big_endian_64",
			"to_char",
			"to_date",
			"to_hex",
			"to_iso8601",
			"to_timestamp",
			"to_unixtime",
			"to_utf8",
			"transform",
			"trim",
			"truncate",
			"typeof",
			"upper",
			"url_decode",
			"url_encode",
			"url_extract_fragment",
			"url_extract_host",
			"url_extract_parameter",
			"url_extract_path",
			"url_extract_port",
			"url_extract_protocol",
			"url_extract_query",
			"uuid",
			"var_pop",
			"var_samp",
			"variance",
			"week",
			"week_of_year",
			"width_bucket",
			"xxhash64",
			"year",
			"year_of_week",
			"yow",
			"zip",
		],
	}
};