version: '2'
services:
  elasticsearch:
    hostname: elasticsearch
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.5.1'
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      discovery.type: single-node
