version: '2'
services:

  mysql:
    image: 'mysql:8.0.21'
    ports:
      - '13306:13306'
    command:
      mysqld --port 13306
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
